// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/generic/constant_or_null.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/generic/error.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/generic/getvariable.cpp>
