// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/main/buffered_data/buffered_data.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/main/buffered_data/simple_buffered_data.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/main/buffered_data/batched_buffered_data.cpp>
