// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/default/default_functions.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/default/default_generator.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/default/default_schemas.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/default/default_table_functions.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/default/default_types.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/default/default_views.cpp>
