// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/serializer/binary_serializer.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/serializer/binary_deserializer.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/serializer/buffered_file_reader.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/serializer/buffered_file_writer.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/serializer/memory_stream.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/serializer/serializer.cpp>
