// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/parser/transform/tableref/transform_base_tableref.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/parser/transform/tableref/transform_join.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/parser/transform/tableref/transform_from.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/parser/transform/tableref/transform_pivot.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/parser/transform/tableref/transform_subquery.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/parser/transform/tableref/transform_table_function.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/parser/transform/tableref/transform_tableref.cpp>
