// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/holistic/approx_top_k.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/holistic/quantile.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/holistic/reservoir_quantile.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/holistic/mad.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/holistic/approximate_quantile.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/holistic/mode.cpp>
