// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/storage/metadata/metadata_manager.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/storage/metadata/metadata_reader.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/storage/metadata/metadata_writer.cpp>
