// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/api/udf_function/test_templated_scalar_udf.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/api/udf_function/test_argumented_scalar_udf.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/api/udf_function/test_templated_vec_udf.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/api/udf_function/test_argumented_vec_udf.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/api/udf_function/test_aggregate_udf.cpp>
