// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/pragma/pragma_functions.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/pragma/pragma_queries.cpp>
