// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/arrow/arrow_test_helper.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/arrow/arrow_roundtrip.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/arrow/arrow_move_children.cpp>
