// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/sql/index/test_art_index.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/sql/index/test_art_keys.cpp>
