// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/secrets/test_custom_secret_storage.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/secrets/test_persistent_secret_permissions.cpp>
