// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/multi_file/base_file_reader.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/multi_file/multi_file_function.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/multi_file/multi_file_list.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/multi_file/multi_file_reader.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/multi_file/multi_file_column_mapper.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/multi_file/union_by_name.cpp>
