// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/scalar/blob/base64.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/scalar/blob/encode.cpp>
