// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/main/chunk_scan_state/query_result.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/main/chunk_scan_state/batched_data_collection.cpp>
