// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/adbc/adbc.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/adbc/driver_manager.cpp>
