// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/adbc/nanoarrow/metadata.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/adbc/nanoarrow/schema.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/adbc/nanoarrow/allocator.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/adbc/nanoarrow/single_batch_array_stream.cpp>
