// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/struct/remap_struct.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/struct/struct_extract.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/struct/struct_pack.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/struct/struct_concat.cpp>
