// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/regression/regr_sxy.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/regression/regr_intercept.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/regression/regr_count.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/regression/regr_r2.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/regression/regr_avg.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/regression/regr_slope.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/aggregate/regression/regr_sxx_syy.cpp>
