// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/scalar/union/union_extract.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/scalar/union/union_value.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/scalar/union/union_tag.cpp>
