// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/appender/bool_data.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/appender/fixed_size_list_data.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/appender/null_data.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/appender/struct_data.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/appender/union_data.cpp>
