// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/persistence/test_persistence.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/persistence/test_locking.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/persistence/test_sequence_crash.cpp>
