// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/storage/buffer/buffer_handle.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/storage/buffer/block_handle.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/storage/buffer/block_manager.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/storage/buffer/buffer_pool.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/storage/buffer/buffer_pool_reservation.cpp>
