// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/scalar/random/random.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/extension/core_functions/scalar/random/setseed.cpp>
