// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/compressed_materialization/compress_integral.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/compressed_materialization/compress_string.cpp>
