// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/operator/add.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/operator/arithmetic.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/operator/multiply.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/operator/subtract.cpp>
