// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/catalog_entry.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/catalog_entry_retriever.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/catalog.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/catalog_search_path.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/catalog_set.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/catalog_transaction.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/duck_catalog.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/dependency_manager.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/dependency_list.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/dependency_catalog_set.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/entry_lookup_info.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/catalog/similar_catalog_entry.cpp>
