// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/arrow_appender.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/arrow_converter.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/arrow_type_extension.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/arrow_merge_event.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/arrow_query_result.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/arrow_util.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/arrow_wrapper.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/physical_arrow_collector.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/physical_arrow_batch_collector.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/common/arrow/schema_metadata.cpp>
