// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/system/aggregate_export.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/system/write_log.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/system/current_transaction_id.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/system/current_connection_id.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/system/current_query_id.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/function/scalar/system/parse_log_message.cpp>
