// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/sql/storage/test_buffer_manager.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/sql/storage/test_checksum.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/sql/storage/test_storage.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/sql/storage/test_database_size.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/test/sql/storage/wal_torn_write.cpp>
