// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/main/capi/cast/utils-c.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/main/capi/cast/from_decimal-c.cpp>
