// Unity Build generated by CMake
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/execution/operator/projection/physical_projection.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/execution/operator/projection/physical_tableinout_function.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/execution/operator/projection/physical_pivot.cpp>
#include </home/runner/work/clickhouse-sql/clickhouse-sql/duckdb/src/execution/operator/projection/physical_unnest.cpp>
